require('dotenv').config();

module.exports = {
    api: 'https://api.baobab.klaytn.net:8651',
    apiInternal: 'https://api.baobab.klaytn.net:8651',
    chainId: 1001,
    privateKey: process.env.KLAY_PRIVATE_KEY,
    feePayerAddress: process.env.KLAY_FEE_PLAYER_ADDRESS,
    feePayerPrivateKey: process.env.KLAY_FEE_PLAYER_PRIVATE_KEY,
    contractAddress: '0x91dFE596ADF7c706eA4E64E3C3FdaF6540E6A00D',
    abi: [
        { constant: true, inputs: [], name: 'isOwner', outputs: [{ name: '', type: 'bool' }], payable: false, stateMutability: 'view', type: 'function', signature: '0x8f32d59b' },
        {
            constant: false,
            inputs: [{ name: 'newOwner', type: 'address' }],
            name: 'transferOwnership',
            outputs: [],
            payable: false,
            stateMutability: 'nonpayable',
            type: 'function',
            signature: '0xf2fde38b',
        },
        {
            anonymous: false,
            inputs: [
                { indexed: false, name: 'idx', type: 'uint256' },
                { indexed: false, name: 'name', type: 'string' },
                { indexed: false, name: 'startTime', type: 'uint256' },
                { indexed: false, name: 'endTime', type: 'uint256' },
            ],
            name: 'AddVote',
            type: 'event',
            signature: '0x90507ca952f6ca87f6e6788d2e13e1123538a235647b3e5bd65c7aa880c7e911',
        },
        {
            anonymous: false,
            inputs: [
                { indexed: false, name: 'idx', type: 'uint256' },
                { indexed: false, name: 'name', type: 'string' },
            ],
            name: 'AddCandidate',
            type: 'event',
            signature: '0x0a63c583b11f468eaa71ea0d4db8b8f20e90db294844b5e0c90d933b0bd5168d',
        },
        {
            anonymous: false,
            inputs: [
                { indexed: true, name: 'previousOwner', type: 'address' },
                { indexed: true, name: 'newOwner', type: 'address' },
            ],
            name: 'OwnershipTransferred',
            type: 'event',
            signature: '0x8be0079c531659141344cd1fd0a4f28419497f9722a3daafe3b4186f6b6457e0',
        },
        {
            constant: true,
            inputs: [{ name: 'idx', type: 'uint256' }],
            name: 'getVote',
            outputs: [
                { name: 'voteIdx', type: 'uint256' },
                { name: 'voteName', type: 'string' },
                { name: 'candIdxes', type: 'uint256[]' },
                { name: 'totalVoteCnt', type: 'uint256' },
                { name: 'startTime', type: 'uint256' },
                { name: 'endTime', type: 'uint256' },
                { name: 'status', type: 'uint256' },
            ],
            payable: false,
            stateMutability: 'view',
            type: 'function',
            signature: '0x5a55c1f0',
        },
        {
            constant: true,
            inputs: [{ name: 'idx', type: 'uint256' }],
            name: 'getCandidate',
            outputs: [
                { name: 'candIdx', type: 'uint256' },
                { name: 'candName', type: 'string' },
                { name: 'voteCnt', type: 'uint256' },
            ],
            payable: false,
            stateMutability: 'view',
            type: 'function',
            signature: '0x35b8e820',
        },
        {
            constant: false,
            inputs: [
                { name: 'name', type: 'string' },
                { name: 'startTime', type: 'uint256' },
                { name: 'endTime', type: 'uint256' },
            ],
            name: 'addVote',
            outputs: [{ name: '', type: 'uint256' }],
            payable: false,
            stateMutability: 'nonpayable',
            type: 'function',
            signature: '0x8f70251f',
        },
        {
            constant: false,
            inputs: [
                { name: 'voteIdx', type: 'uint256' },
                { name: 'name', type: 'string' },
            ],
            name: 'addCandidate',
            outputs: [{ name: '', type: 'uint256' }],
            payable: false,
            stateMutability: 'nonpayable',
            type: 'function',
            signature: '0x1750a3d0',
        },
        {
            constant: false,
            inputs: [
                { name: 'voteIdx', type: 'uint256' },
                { name: 'candIdx', type: 'uint256' },
                { name: 'renounce', type: 'bool' },
            ],
            name: 'vote',
            outputs: [],
            payable: false,
            stateMutability: 'nonpayable',
            type: 'function',
            signature: '0x6a18ff7a',
        },
    ],
};
